// Catálogo CIE-10 (OMS) — capítulo K00-K14: enfermedades de la cavidad
// oral, las glándulas salivales y los maxilares. Es la sección que un
// odontólogo usa en la práctica real — el catálogo CIE-10 completo tiene
// más de 14,000 códigos, casi todos ajenos a esta especialidad.

export const CATALOGO_CIE10 = [
  { codigo: 'K00.0', descripcion: 'Anodoncia' },
  { codigo: 'K00.1', descripcion: 'Dientes supernumerarios' },
  { codigo: 'K00.2', descripcion: 'Anomalías del tamaño y la forma de los dientes' },
  { codigo: 'K00.3', descripcion: 'Moteado dental' },
  { codigo: 'K00.4', descripcion: 'Trastornos de la formación dental' },
  { codigo: 'K00.5', descripcion: 'Trastornos hereditarios de la estructura dentaria' },
  { codigo: 'K00.6', descripcion: 'Trastornos de la erupción dentaria' },
  { codigo: 'K00.7', descripcion: 'Síndrome de la erupción dentaria' },
  { codigo: 'K00.8', descripcion: 'Otros trastornos del desarrollo dentario' },
  { codigo: 'K00.9', descripcion: 'Trastorno del desarrollo dentario, no especificado' },
  { codigo: 'K01.0', descripcion: 'Dientes retenidos' },
  { codigo: 'K01.1', descripcion: 'Dientes impactados' },
  { codigo: 'K02.0', descripcion: 'Caries limitada al esmalte' },
  { codigo: 'K02.1', descripcion: 'Caries de la dentina' },
  { codigo: 'K02.2', descripcion: 'Caries del cemento' },
  { codigo: 'K02.3', descripcion: 'Caries dental detenida' },
  { codigo: 'K02.4', descripcion: 'Odontoclasia' },
  { codigo: 'K02.8', descripcion: 'Otras caries dentales' },
  { codigo: 'K02.9', descripcion: 'Caries dental, no especificada' },
  { codigo: 'K03.0', descripcion: 'Atrición excesiva de los dientes' },
  { codigo: 'K03.1', descripcion: 'Abrasión de los dientes' },
  { codigo: 'K03.2', descripcion: 'Erosión de los dientes' },
  { codigo: 'K03.3', descripcion: 'Reabsorción patológica de los dientes' },
  { codigo: 'K03.4', descripcion: 'Hipercementosis' },
  { codigo: 'K03.5', descripcion: 'Anquilosis dental' },
  { codigo: 'K03.6', descripcion: 'Depósitos [acumulaciones] en los dientes' },
  { codigo: 'K03.7', descripcion: 'Cambios de color post-eruptivos en los tejidos dentarios duros' },
  { codigo: 'K03.8', descripcion: 'Otras enfermedades especificadas de los tejidos duros de los dientes' },
  { codigo: 'K03.9', descripcion: 'Enfermedad de los tejidos duros de los dientes, no especificada' },
  { codigo: 'K04.0', descripcion: 'Pulpitis' },
  { codigo: 'K04.1', descripcion: 'Necrosis de la pulpa' },
  { codigo: 'K04.2', descripcion: 'Degeneración de la pulpa' },
  { codigo: 'K04.3', descripcion: 'Formación anormal de tejido duro en la pulpa' },
  { codigo: 'K04.4', descripcion: 'Periodontitis apical aguda de origen pulpar' },
  { codigo: 'K04.5', descripcion: 'Periodontitis apical crónica' },
  { codigo: 'K04.6', descripcion: 'Absceso periapical con fístula' },
  { codigo: 'K04.7', descripcion: 'Absceso periapical sin fístula' },
  { codigo: 'K04.8', descripcion: 'Quiste radicular' },
  { codigo: 'K04.9', descripcion: 'Otras enfermedades de la pulpa y de los tejidos periapicales, no especificadas' },
  { codigo: 'K05.0', descripcion: 'Gingivitis aguda' },
  { codigo: 'K05.1', descripcion: 'Gingivitis crónica' },
  { codigo: 'K05.2', descripcion: 'Periodontitis aguda' },
  { codigo: 'K05.3', descripcion: 'Periodontitis crónica' },
  { codigo: 'K05.4', descripcion: 'Periodontosis' },
  { codigo: 'K05.5', descripcion: 'Otras enfermedades periodontales' },
  { codigo: 'K05.6', descripcion: 'Enfermedad periodontal, no especificada' },
  { codigo: 'K06.0', descripcion: 'Retracción gingival' },
  { codigo: 'K06.1', descripcion: 'Hiperplasia gingival' },
  { codigo: 'K06.2', descripcion: 'Lesiones de la encía y del reborde alveolar edéntulo asociadas a traumatismo' },
  { codigo: 'K06.8', descripcion: 'Otros trastornos especificados de la encía y del reborde alveolar edéntulo' },
  { codigo: 'K06.9', descripcion: 'Trastorno de la encía y del reborde alveolar edéntulo, no especificado' },
  { codigo: 'K07.0', descripcion: 'Anomalías principales del tamaño de los maxilares' },
  { codigo: 'K07.1', descripcion: 'Anomalías de la relación maxilobasilar-craneal' },
  { codigo: 'K07.2', descripcion: 'Anomalías de la relación entre arcos dentales' },
  { codigo: 'K07.3', descripcion: 'Anomalías de la posición del diente' },
  { codigo: 'K07.4', descripcion: 'Maloclusión, no especificada' },
  { codigo: 'K07.5', descripcion: 'Anomalías dentofaciales funcionales' },
  { codigo: 'K07.6', descripcion: 'Trastornos de la articulación temporomandibular' },
  { codigo: 'K07.8', descripcion: 'Otras anomalías dentofaciales' },
  { codigo: 'K07.9', descripcion: 'Anomalía dentofacial, no especificada' },
  { codigo: 'K08.0', descripcion: 'Exfoliación de los dientes debida a causas sistémicas' },
  { codigo: 'K08.1', descripcion: 'Pérdida de dientes debida a accidente, extracción o enfermedad periodontal local' },
  { codigo: 'K08.2', descripcion: 'Atrofia del reborde alveolar edéntulo' },
  { codigo: 'K08.3', descripcion: 'Raíz dental retenida' },
  { codigo: 'K08.8', descripcion: 'Otros trastornos especificados de los dientes y de sus estructuras de sostén' },
  { codigo: 'K08.9', descripcion: 'Trastorno de los dientes y de sus estructuras de sostén, no especificado' },
  { codigo: 'K09.0', descripcion: 'Quistes odontogénicos del desarrollo' },
  { codigo: 'K09.1', descripcion: 'Quistes del desarrollo (no odontogénicos) de la región bucal' },
  { codigo: 'K09.2', descripcion: 'Otros quistes de los maxilares' },
  { codigo: 'K09.8', descripcion: 'Otros quistes especificados de la región bucal, no clasificados en otra parte' },
  { codigo: 'K09.9', descripcion: 'Quiste de la región bucal, no especificado' },
  { codigo: 'K10.0', descripcion: 'Trastornos del desarrollo de los maxilares' },
  { codigo: 'K10.1', descripcion: 'Granuloma central de células gigantes' },
  { codigo: 'K10.2', descripcion: 'Afecciones inflamatorias de los maxilares' },
  { codigo: 'K10.3', descripcion: 'Alveolitis del maxilar' },
  { codigo: 'K10.8', descripcion: 'Otras enfermedades especificadas de los maxilares' },
  { codigo: 'K10.9', descripcion: 'Enfermedad de los maxilares, no especificada' },
  { codigo: 'K11.0', descripcion: 'Atrofia de la glándula salival' },
  { codigo: 'K11.1', descripcion: 'Hipertrofia de la glándula salival' },
  { codigo: 'K11.2', descripcion: 'Sialoadenitis' },
  { codigo: 'K11.3', descripcion: 'Absceso de la glándula salival' },
  { codigo: 'K11.4', descripcion: 'Fístula de la glándula salival' },
  { codigo: 'K11.5', descripcion: 'Sialolitiasis' },
  { codigo: 'K11.6', descripcion: 'Mucocele de la glándula salival' },
  { codigo: 'K11.7', descripcion: 'Trastornos de la secreción salival' },
  { codigo: 'K11.8', descripcion: 'Otras enfermedades de las glándulas salivales' },
  { codigo: 'K11.9', descripcion: 'Enfermedad de la glándula salival, no especificada' },
  { codigo: 'K12.0', descripcion: 'Afta bucal recurrente' },
  { codigo: 'K12.1', descripcion: 'Otras formas de estomatitis' },
  { codigo: 'K12.2', descripcion: 'Celulitis y absceso de la boca' },
  { codigo: 'K12.3', descripcion: 'Mucositis oral (ulcerativa)' },
  { codigo: 'K13.0', descripcion: 'Enfermedades de los labios' },
  { codigo: 'K13.1', descripcion: 'Mordedura del carrillo y del labio' },
  { codigo: 'K13.2', descripcion: 'Leucoplasia y otras alteraciones del epitelio bucal, incluso de la lengua' },
  { codigo: 'K13.3', descripcion: 'Leucoplasia vellosa' },
  { codigo: 'K13.4', descripcion: 'Lesiones granulomatosas y granulomatoides de la mucosa oral' },
  { codigo: 'K13.5', descripcion: 'Fibrosis submucosa oral' },
  { codigo: 'K13.6', descripcion: 'Hiperplasia irritativa de la mucosa oral' },
  { codigo: 'K13.7', descripcion: 'Otras lesiones y las no especificadas de la mucosa oral' },
  { codigo: 'K14.0', descripcion: 'Glositis' },
  { codigo: 'K14.1', descripcion: 'Lengua geográfica' },
  { codigo: 'K14.2', descripcion: 'Glositis romboidal media' },
  { codigo: 'K14.3', descripcion: 'Hipertrofia de las papilas linguales' },
  { codigo: 'K14.4', descripcion: 'Atrofia de las papilas linguales' },
  { codigo: 'K14.5', descripcion: 'Lengua plegada' },
  { codigo: 'K14.6', descripcion: 'Glosodinia' },
  { codigo: 'K14.8', descripcion: 'Otras enfermedades de la lengua' },
  { codigo: 'K14.9', descripcion: 'Enfermedad de la lengua, no especificada' }
]

// Búsqueda simple por código o descripción — sin librerías nuevas, el
// catálogo es chico (K00-K14) y no necesita nada más sofisticado.
export function buscarCie10(termino) {
  if (!termino || termino.trim().length < 2) return []
  const t = termino.toLowerCase().trim()
  return CATALOGO_CIE10.filter(
    (c) => c.codigo.toLowerCase().includes(t) || c.descripcion.toLowerCase().includes(t)
  ).slice(0, 15)
}
